spring:
  profiles:
    active: local
---
spring.profiles: local, test
spring.profiles.include: oauth, aws, console-logging

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      open-in-view: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

debug: true

---
spring.profiles: dev
spring.profiles.include: file-info-logging, file-error-logging

logging:
  file:
    path: /home/ec2-user
