spring:
  profiles:
    active: local
---
spring.profiles: local
spring.profiles.include: oauth, aws, console-logging

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/gaejangmo?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul
      username: root
      password: password
debug: true

---
spring.profiles: dev
spring.profiles.include: file-info-logging, file-error-logging

logging:
  file:
    path: /home/ec2-user
