spring:
  profiles:
    active: local
---
spring.profiles: local, test
spring.profiles.include: oauth

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      open-in-view: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

debug: true

oauth:
  redirect-url: "localhost:3000/"

